# Basic workflow to generate a macos binary

name: MacOS Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-binary:
    runs-on: macos-latest
    name: Generate Binary File
    steps:
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        architecture: x64 # The target architecture (x86, x64) of the Python interpreter.
    - name: Download Craft
      run: curl https://raw.githubusercontent.com/itachi1706/craft/master/setup/CraftBootstrap.py -o setup.py
    - name: Install Craft
      run: python3 setup.py --headless --prefix ~/CraftRoot --headless
    - name: Get KDE Connect Dependencies
      run: source ~/CraftRoot/craft/craftenv.sh && craft --install-deps kdeconnect-kde
    - name: Build KDE Connect
      run: source ~/CraftRoot/craft/craftenv.sh && craft kdeconnect-kde
    - name: Package KDE Connect
      run: source ~/CraftRoot/craft/craftenv.sh && craft --package kdeconnect-kde
    - name: List dmg file that should be found
      run: ls ~/CraftRoot/tmp/
    #- name: Upload DMG files as artifacts
    #  uses: actions/upload-artifact@v2
    #  with:
        # Artifact name
    #    name: # optional
        # A file, directory or wildcard pattern that describes what to upload
    #    path: 
