# Basic workflow to generate a macos binary

name: Build MacOS Binary

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Generate Binary:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        architecture: x64 # The target architecture (x86, x64) of the Python interpreter.
    - name: Install XCode
      run: xcode-select --install
    #- name: Fix Craft install
    #  run: /Applications/Python3.8/Install/Certificates.command
    - name: Install Craft
      run: curl https://raw.githubusercontent.com/KDE/craft/master/setup/CraftBootstrap.py -o setup.py && python3 setup.py --prefix ~/CraftRoot
    - name: Setup Craft
      run: source ~/CraftRoot/craft/craftenv.sh
    - name: Generate stuff
      run: craft kate
    - name: List stuff
      run: ls

    # Runs a set of commands using the runners shell
    #- name: Run a multi-line script
    #  run: |
    #    echo Add other actions to build,
    #    echo test, and deploy your project.
